import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import MantineProvider from "../components/layouts/MantineProvider";
import QueryClientProvider from "../components/layouts/QueryClientProvider";
import SessionProvider from "@/components/layouts/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MantineProvider>
          <QueryClientProvider>{children}</QueryClientProvider>
        </MantineProvider>
        <NextTopLoader />
      </body>
    </html>
  );
}
